name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 git history를 가져옵니다

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_separator: ","
      
      - name: GPT Code Review
        uses: abinoda/gpt-pull-request-review@v1.0.1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          model: "gpt-4"
          review_comment_prefix: "🤖 GPT Code Review:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}